import { firebaseConfig } from './firebase-config.js?v=8';

const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const ADMIN_NAME = 'ASHISH RATHOR';
const state = { user: null, db: null, auth: null, firebase: false, isAdmin: false, materials: [], doubts: [], songs: [], leaders: [], community: [], listeners: {} };
const demoMaterials = [
  {id:'1',title:'Motion & Laws — Quick Notes',description:'Core formulas, graphs and solved examples.',subject:'Physics',type:'PDF',url:'#'},
  {id:'2',title:'Organic Chemistry Reactions',description:'Important named reactions and revision map.',subject:'Chemistry',type:'PDF',url:'#'},
  {id:'3',title:'Human Physiology Revision',description:'Chapter-wise diagrams and one-shot notes.',subject:'Biology',type:'Notes',url:'#'},
];

function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function openView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item,.mobile-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('#pageTitle').textContent={home:'RATHOD HUB 3.0',materials:'Study Material',chat:'Live Chat',doubts:'Doubt Room',music:'Focus Music',leaderboard:'Leaderboard',community:'Community',admin:'Admin Sync'}[id];$('.sidebar').classList.remove('open');location.hash=id==='home'?'':id;stopHiddenListeners(id);if(state.firebase&&state.user)subscribeView(id)}
$$('[data-view]').forEach(b=>b.onclick=()=>openView(b.dataset.view));$$('[data-open]').forEach(b=>b.onclick=()=>openView(b.dataset.open));$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');

function esc(s=''){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function fmt(ts){try{const d=ts?.toDate?ts.toDate():new Date(ts||Date.now());return d.toLocaleString([],{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}catch{return 'Now'}}
const neetSubjects = [
  {name:'Physics', code:'Ph', icon:'⚛', tone:'violet'},
  {name:'Physical Chemistry', code:'PC', icon:'⚗', tone:'orange'},
  {name:'Organic Chemistry', code:'OC', icon:'⌬', tone:'rose'},
  {name:'Inorganic Chemistry', code:'IC', icon:'◫', tone:'blue'},
  {name:'Botany', code:'Bo', icon:'⌁', tone:'green'},
  {name:'Zoology', code:'Zo', icon:'♧', tone:'cyan'}
];
const folderTemplates = [
  {name:'Concise Notes', code:'SM-01', icon:'▤', note:'Quick revision PDFs'},
  {name:'Practice Sheets', code:'SM-02', icon:'✓', note:'Chapter-wise questions'},
  {name:'Handwritten Notes', code:'SM-03', icon:'✎', note:'Premium class notes'},
  {name:'NEET PYQ', code:'SM-04', icon:'◎', note:'Previous year questions'},
  {name:'NCERT Discussion', code:'SM-05', icon:'N', note:'Line-by-line NCERT'},
  {name:'Kattar Practice', code:'SM-06', icon:'⚡', note:'High-level practice'}
];
let catalog = {level:'subjects', subject:null, folder:null};
function materialCount(subject,folder){return state.materials.filter(x=>(!subject||x.subject===subject)&&(!folder||x.folder===folder)).length}
function renderCatalog(){
 const grid=$('#catalogGrid'), q=$('#materialSearch').value.toLowerCase();
 $('#catalogBack').classList.toggle('hidden',catalog.level==='subjects');
 if(catalog.level==='subjects'){
  $('#catalogEyebrow').textContent='ALL CLASSES';$('#catalogTitle').textContent='Choose your subject';$('#catalogSubtitle').textContent='Complete NEET library — Physics, Chemistry and Biology.';$('#materialSearch').placeholder='Search subjects…';
  const rows=neetSubjects.filter(x=>x.name.toLowerCase().includes(q));
  grid.className='catalog-grid subject-catalog';grid.innerHTML=rows.map(x=>`<button class="subject-card ${x.tone}" data-catalog-subject="${esc(x.name)}"><span class="catalog-icon">${x.icon}</span><div><span>${x.code}</span><b>${x.name}</b><small>${materialCount(x.name)} PDFs available</small></div><em>›</em></button>`).join('');$('#materialsEmpty').classList.add('hidden');
 } else if(catalog.level==='folders'){
  $('#catalogEyebrow').textContent='SUBJECT LIBRARY';$('#catalogTitle').textContent=catalog.subject;$('#catalogSubtitle').textContent='Open a folder to view its PDFs.';$('#materialSearch').placeholder='Search folders…';
  const rows=folderTemplates.filter(x=>`${x.name} ${x.note}`.toLowerCase().includes(q));
  grid.className='catalog-grid folder-catalog';grid.innerHTML=rows.map(x=>`<button class="folder-card" data-catalog-folder="${esc(x.name)}"><span class="folder-code">${x.code}</span><span class="folder-icon">${x.icon}</span><div><b>${x.name}</b><small>${x.note}</small><span>${materialCount(catalog.subject,x.name)} PDFs</span></div><em>›</em></button>`).join('');$('#materialsEmpty').classList.add('hidden');
 } else {
  $('#catalogEyebrow').textContent=catalog.subject.toUpperCase();$('#catalogTitle').textContent=catalog.folder;$('#catalogSubtitle').textContent='Open or download your study PDFs.';$('#materialSearch').placeholder='Search PDFs…';
  const rows=state.materials.filter(x=>x.subject===catalog.subject&&x.folder===catalog.folder&&`${x.title} ${x.description||''}`.toLowerCase().includes(q));
  grid.className='catalog-grid pdf-catalog';grid.innerHTML=rows.map((x,i)=>`<article class="pdf-row"><span class="pdf-icon">PDF</span><div><b>${esc(x.title)}</b><small>${esc(x.description||catalog.subject+' study material')}</small></div><span class="pdf-size">${esc(x.size||'PDF')}</span><a href="${esc(x.url||'#')}" target="_blank" rel="noopener">Open</a></article>`).join('');$('#materialsEmpty').classList.toggle('hidden',rows.length>0);
 }
 $('#materialCount').textContent=state.materials.length;
 grid.querySelectorAll('[data-catalog-subject]').forEach(b=>b.onclick=()=>{catalog={level:'folders',subject:b.dataset.catalogSubject,folder:null};$('#materialSearch').value='';renderCatalog()});
 grid.querySelectorAll('[data-catalog-folder]').forEach(b=>b.onclick=()=>{catalog.level='pdfs';catalog.folder=b.dataset.catalogFolder;$('#materialSearch').value='';renderCatalog()});
}
$('#materialSearch').oninput=renderCatalog;
$('#catalogBack').onclick=()=>{if(catalog.level==='pdfs'){catalog.level='folders';catalog.folder=null}else{catalog={level:'subjects',subject:null,folder:null}};$('#materialSearch').value='';renderCatalog()};
$$('[data-subject-open]').forEach(b=>b.addEventListener('click',()=>{catalog={level:'folders',subject:b.dataset.subjectOpen,folder:null};$('#materialSearch').value='';renderCatalog()}));
function renderDoubts(){const rows=state.doubts;$('#doubtsList').innerHTML=rows.map(x=>`<article class="doubt"><div><span class="subject">${esc(x.subject)}</span><h3>${esc(x.text)}</h3><p>Asked by ${esc(x.authorName||'Student')}</p></div><time>${fmt(x.createdAt)}</time></article>`).join('');$('#doubtsEmpty').classList.toggle('hidden',rows.length>0);$('#doubtCount').textContent=rows.length}
const SUPABASE_URL='https://fezyljxjbgefaqroxorl.supabase.co';
const SUPABASE_KEY='sb_publishable_UQ0y1axzT6jsesDmz1JHPA_j2budIh3';
async function supabaseFetch(path,options={}){const r=await fetch(SUPABASE_URL+path,{...options,headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json',...(options.headers||{})}});if(!r.ok)throw new Error('Supabase '+r.status);return r.json()}
function renderSongs(){const root=$('#songsGrid');$('#songCount').textContent=state.songs.length;if(!state.songs.length){root.innerHTML='<div class="empty"><span>♫</span><b>No ready songs found</b><p>Add tracks in the existing RathodHub song library.</p></div>';return}root.innerHTML=state.songs.map((x,i)=>`<button class="song-row" data-song-index="${i}"><span class="song-no">${String(i+1).padStart(2,'0')}</span><span class="song-cover">♫</span><span class="song-meta"><b>${esc(x.title)}</b><small>Rathod VIP • Focus track</small></span><span class="play-circle">▶</span></button>`).join('');root.querySelectorAll('[data-song-index]').forEach(b=>b.onclick=()=>playSong(Number(b.dataset.songIndex)))}
function songSources(x){const a=[];const audio=x.audioUrl||x.audio_url,driveId=x.driveFileId||x.drive_file_id;if(audio&&!String(audio).includes('rathod-question-archive-production.up.railway.app'))a.push(audio);if(driveId&&String(driveId).startsWith('b2_'))a.push('https://rathod-hub-audio.sanatanirambhakt73.workers.dev/'+encodeURIComponent(driveId)+'.mp3');return [...new Set(a)]}
function showDrivePlayer(id){const audio=$('#globalAudio'),frame=$('#drivePlayer'),link=$('#driveOpen');audio.pause();audio.removeAttribute('src');audio.load();audio.classList.add('hidden');frame.src='https://drive.google.com/file/d/'+encodeURIComponent(id)+'/preview';frame.classList.remove('hidden');link.href='https://drive.google.com/file/d/'+encodeURIComponent(id)+'/view';link.classList.remove('hidden');toast('Legacy Drive player opened — tap play')}
function playSong(i){const x=state.songs[i],audio=$('#globalAudio'),frame=$('#drivePlayer'),link=$('#driveOpen'),sources=songSources(x),driveId=x?.driveFileId||x?.drive_file_id;if(!x)return;$('#nowTitle').textContent=x.title;audio.classList.remove('hidden');frame.classList.add('hidden');frame.src='about:blank';link.classList.add('hidden');delete audio.dataset.fallbackTried;audio.dataset.sources=JSON.stringify(sources);audio.dataset.sourceIndex='0';audio.dataset.driveId=driveId||'';if(!sources.length&&driveId&&!String(driveId).startsWith('b2_'))showDrivePlayer(driveId);else if(sources.length){audio.src=sources[0];audio.load();audio.play().catch(()=>{})}else toast('Audio source unavailable');$$('.song-row').forEach((r,n)=>r.classList.toggle('playing',n===i))}
$('#globalAudio').addEventListener('error',()=>{const a=$('#globalAudio'),sources=JSON.parse(a.dataset.sources||'[]'),next=Number(a.dataset.sourceIndex||0)+1;if(next<sources.length){a.dataset.sourceIndex=String(next);a.src=sources[next];a.load();a.play().catch(()=>{});return}const id=a.dataset.driveId;if(id&&!String(id).startsWith('b2_'))showDrivePlayer(id);else toast('Song source offline — Admin R2 sync needed')});
function initials(name='S'){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'S'}
function avatar(x,cls=''){return x.pfp_url?`<img class="rank-avatar ${cls}" src="${esc(x.pfp_url)}" alt="${esc(x.name)}" referrerpolicy="no-referrer">`:`<span class="rank-avatar ${cls}">${esc(initials(x.name))}</span>`}
function renderLeaderboard(){const rows=state.leaders.map((x,i)=>({...x,rank:i+1,league_level:x.league_level||x.leagueLevel,group_no:x.group_no||x.groupNo,season_xp:x.season_xp??x.seasonXp,pfp_url:x.pfp_url||x.avatarUrl}));const podium=$('#podium'),list=$('#leaderboardRows');if(!rows.length){podium.innerHTML='<div class="empty"><span>🏆</span><b>Leaderboard connection pending</b><p>The safe public leaderboard endpoint needs to be enabled.</p></div>';list.innerHTML='';return}const top=rows.slice(0,3),order=[top[1],top[0],top[2]].filter(Boolean);podium.innerHTML=order.map(x=>`<article class="podium-place p${x.rank}"><span class="medal">${x.rank==1?'🥇':x.rank==2?'🥈':'🥉'}</span>${avatar(x,'large')}<b>${esc(x.name)}</b><small>League ${x.league_level}</small><strong>${x.season_xp} XP</strong><i>${x.rank}</i></article>`).join('');list.innerHTML=rows.map(x=>`<div class="leader-row"><b class="rank-num">${x.rank}</b>${avatar(x)}<div><b>${esc(x.name)}</b><small>League ${x.league_level} • Group ${x.group_no}</small></div><strong>${x.season_xp}<small> XP</small></strong></div>`).join('')}
async function loadSupabaseFeatures(){try{state.songs=await supabaseFetch('/rest/v1/rh_song_library?select=id,title,audio_url,drive_url,drive_file_id,status,created_at&status=eq.ready&order=created_at.desc&limit=100');renderSongs()}catch(e){console.warn(e);renderSongs()}try{state.leaders=await supabaseFetch('/rest/v1/rpc/get_public_leaderboard',{method:'POST',body:JSON.stringify({p_limit:50})});renderLeaderboard()}catch(e){console.warn(e);renderLeaderboard()}}
const reactionTypes=[['like','👍'],['love','❤️'],['laugh','😂'],['fire','🔥'],['helpful','💡']];
function renderCommunity(){const root=$('#communityPosts');if(!state.community.length){root.innerHTML='<div class="empty"><span>☻</span><b>Be the first to post</b><p>Community abhi bilkul fresh hai.</p></div>';return}root.innerHTML=state.community.map(p=>{const reactions=p.reactions||{},values=Object.values(reactions),comments=Array.isArray(p.comments)?p.comments:[];return `<article class="community-post card" data-post="${p.id}"><header><span class="post-avatar">${esc(initials(p.name||'Student'))}</span><div><b>${esc(p.name||'Student')}</b><small>${fmt(p.createdAt)}</small></div><span class="post-menu">•••</span></header><p>${esc(p.text||'')}</p><div class="reaction-summary">${reactionTypes.map(([k,e])=>values.filter(v=>v===k).length?`<span>${e} ${values.filter(v=>v===k).length}</span>`:'').join('')}<small>${comments.length} comments</small></div><div class="reaction-bar">${reactionTypes.map(([k,e])=>`<button data-react="${k}" class="${reactions[state.user?.uid]===k?'active':''}">${e}</button>`).join('')}<button data-comment>💬 Reply</button></div><div class="comment-list">${comments.slice(-8).map(c=>`<div class="comment"><span>${esc(initials(c.name||'S'))}</span><div><b>${esc(c.name||'Student')}</b>${c.replyTo?`<small> replied to ${esc(c.replyTo)}</small>`:''}<p>${esc(c.text||'')}</p><button data-reply-to="${esc(c.name||'Student')}">Reply</button></div></div>`).join('')}</div>${comments.length?'<button class="show-comments">Recent replies shown</button>':''}</article>`}).join('');root.querySelectorAll('[data-post]').forEach(card=>{const id=card.dataset.post;card.querySelectorAll('[data-react]').forEach(b=>b.onclick=()=>reactPost(id,b.dataset.react));card.querySelector('[data-comment]').onclick=()=>commentPost(id);card.querySelectorAll('[data-reply-to]').forEach(b=>b.onclick=()=>commentPost(id,b.dataset.replyTo))})}
async function reactPost(id,type){if(!state.user)return toast('Name se login karein');const post=state.community.find(x=>x.id===id),current=post?.reactions?.[state.user.uid],a=state.api;try{await a.updateDoc(a.doc(state.db,'community_posts',id),{['reactions.'+state.user.uid]:current===type?a.deleteField():type});toast('Reaction saved ✓')}catch(e){console.error(e);toast(navigator.onLine?'Community permission update हो रही है':'Offline — online होते ही फिर try करें')}}
async function commentPost(id,replyTo=''){if(!state.user)return toast('Name se login karein');const text=prompt(replyTo?`Reply to ${replyTo}`:'Write a comment')?.trim();if(!text)return;const a=state.api;try{await a.updateDoc(a.doc(state.db,'community_posts',id),{comments:a.arrayUnion({id:crypto.randomUUID(),uid:state.user.uid,name:state.user.displayName||'Student',text:text.slice(0,400),replyTo,createdAt:new Date().toISOString()})});toast('Reply posted ✓')}catch(e){console.error(e);toast(navigator.onLine?'Reply permission update हो रही है':'Offline — reply online होकर भेजें')}}
function addMessage(x){const el=document.createElement('article');el.className=`message ${x.uid===state.user?.uid?'mine':''}`;el.innerHTML=`<header><b>${esc(x.authorName||'Student')}</b><time>${fmt(x.createdAt)}</time></header><p>${esc(x.text)}</p>`;$('#chatMessages').append(el);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight}

async function initFirebase(){const configured=!Object.values(firebaseConfig).some(v=>v.includes('PASTE_'));if(!configured){startDemo();return}try{
 const [{initializeApp},{getAuth,onAuthStateChanged,signInAnonymously,signInWithEmailAndPassword,signOut,updateProfile},{getFirestore,collection,addDoc,query,orderBy,limit,onSnapshot,serverTimestamp,doc,getDoc,updateDoc,arrayUnion,deleteField,enableMultiTabIndexedDbPersistence}] = await Promise.all([
  import('https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js')]);
 const app=initializeApp(firebaseConfig);state.auth=getAuth(app);state.db=getFirestore(app);state.api={collection,addDoc,query,orderBy,limit,onSnapshot,serverTimestamp,doc,getDoc,updateDoc,arrayUnion,deleteField,signInAnonymously,signInWithEmailAndPassword,signOut,updateProfile};state.firebase=true;enableMultiTabIndexedDbPersistence(state.db).catch(()=>{});$('#connectionBadge').textContent='Firebase connected';$('#connectionBadge').classList.add('online');
 onAuthStateChanged(state.auth,async u=>{if(!u){try{await signInAnonymously(state.auth)}catch(e){console.error(e);startDemo()}return}state.user=u;state.isAdmin=false;try{state.isAdmin=(await state.api.getDoc(state.api.doc(state.db,'admins',u.uid))).exists()}catch{}renderAuth();subscribeView(location.hash.slice(1)||'home')});
 }catch(e){console.error(e);toast('Firebase connection failed — demo mode started');startDemo()}}
function startDemo(){state.materials=demoMaterials;state.doubts=JSON.parse(localStorage.getItem('rh_doubts')||'[]');state.user={uid:localStorage.getItem('rh_uid')||crypto.randomUUID(),displayName:localStorage.getItem('rh_name')||'Guest Student'};localStorage.setItem('rh_uid',state.user.uid);renderAuth();renderCatalog();renderDoubts();const welcome={authorName:'Rathod Hub',text:'Welcome! Firebase connect karne ke baad yeh chat sabhi devices par live hogi.',createdAt:Date.now()};addMessage(welcome)}
function renderAuth(){if(!state.user){$('#authBox').innerHTML='<button id="loginBtn" class="primary full">Enter your name</button>';$('#loginBtn').onclick=login;return}$('#authBox').innerHTML=`<button id="profileBtn" class="ghost full" title="Tap to set your name">${state.isAdmin?'🛡️':'👤'} ${esc(state.isAdmin?ADMIN_NAME:(state.user.displayName||'Guest Student'))}</button>`;$('#profileBtn').onclick=login;$$('.admin-only').forEach(x=>x.classList.toggle('hidden',!state.isAdmin))}
async function adminLogin(e){e.preventDefault();if(!state.firebase)return;const status=$('#adminLoginStatus'),button=$('#adminLoginSubmit'),email=$('#adminLoginEmail').value.trim(),password=$('#adminLoginPassword').value;status.textContent='Secure login check हो रहा है…';button.disabled=true;try{const cred=await state.api.signInWithEmailAndPassword(state.auth,email,password),user=cred.user,admin=(await state.api.getDoc(state.api.doc(state.db,'admins',user.uid))).exists();if(!admin){await state.api.signOut(state.auth);throw new Error('यह account authorized admin list में नहीं है।')}if(user.displayName!==ADMIN_NAME)await state.api.updateProfile(user,{displayName:ADMIN_NAME});state.user=user;state.isAdmin=true;$('#adminLoginDialog').close();$('#adminLoginPassword').value='';renderAuth();openView('admin');toast('Welcome, '+ADMIN_NAME+' ✓')}catch(err){status.textContent=err.code==='auth/invalid-credential'?'Email या password गलत है।':(err.message||'Admin login failed');try{if(!state.auth.currentUser)await state.api.signInAnonymously(state.auth)}catch{}}finally{button.disabled=false}}
$('#adminLoginOpen').onclick=()=>{$('#adminLoginStatus').textContent='';$('#adminLoginDialog').showModal()};$('#adminLoginClose').onclick=()=>$('#adminLoginDialog').close();$('#adminLoginForm').onsubmit=adminLogin;
async function login(){if(!state.firebase)return;try{const user=state.auth.currentUser||(await state.api.signInAnonymously(state.auth)).user;const name=prompt('Apna naam daaliye',user.displayName||'Student')?.trim();if(!name)return;await state.api.updateProfile(user,{displayName:name.slice(0,40)});state.user=user;renderAuth();subscribeView(location.hash.slice(1)||'home');toast('Welcome, '+name+' ✓')}catch(e){toast(e.message)}}
const VIEW_LISTENER={materials:'materials',doubts:'doubts',chat:'messages',music:'songs',leaderboard:'leaders',community:'community'};
function stopHiddenListeners(view){const keep=VIEW_LISTENER[view]||'';for(const [key,unsubscribe] of Object.entries(state.listeners)){if(key!==keep){try{unsubscribe()}catch{}delete state.listeners[key]}}}
function listenOnce(key,queryRef,onData,onError){if(state.listeners[key])return;state.listeners[key]=state.api.onSnapshot(queryRef,onData,onError||((e)=>console.warn(key+' listener:',e)))}
function subscribeView(view){if(!state.firebase||!state.user||!state.api)return;const a=state.api;
 if(view==='materials')listenOnce('materials',a.query(a.collection(state.db,'materials'),a.orderBy('createdAt','desc'),a.limit(100)),s=>{state.materials=s.docs.map(d=>({id:d.id,...d.data()}));renderCatalog()});
 if(view==='doubts')listenOnce('doubts',a.query(a.collection(state.db,'doubts'),a.orderBy('createdAt','desc'),a.limit(100)),s=>{state.doubts=s.docs.map(d=>({id:d.id,...d.data()}));renderDoubts()});
 if(view==='chat')listenOnce('messages',a.query(a.collection(state.db,'messages'),a.orderBy('createdAt','asc'),a.limit(100)),s=>{$('#chatMessages').innerHTML='';s.docs.forEach(d=>addMessage(d.data()))});
 if(view==='music')listenOnce('songs',a.query(a.collection(state.db,'songs'),a.orderBy('createdAt','desc'),a.limit(100)),s=>{const rows=s.docs.map(d=>({id:d.id,...d.data()}));if(rows.length){state.songs=rows;renderSongs()}});
 if(view==='leaderboard')listenOnce('leaders',a.query(a.collection(state.db,'legacy_leaderboard'),a.orderBy('seasonXp','desc'),a.limit(100)),s=>{const rows=s.docs.map(d=>({id:d.id,...d.data()}));if(rows.length){state.leaders=rows;renderLeaderboard()}});
 if(view==='community')listenOnce('community',a.query(a.collection(state.db,'community_posts'),a.orderBy('createdAt','desc'),a.limit(50)),s=>{state.community=s.docs.map(d=>({id:d.id,...d.data()}));localStorage.setItem('rh3_community_cache',JSON.stringify(state.community.map(x=>({...x,createdAt:x.createdAt?.toDate?x.createdAt.toDate().toISOString():x.createdAt}))));renderCommunity()},e=>{console.warn('Community listener:',e);try{state.community=JSON.parse(localStorage.getItem('rh3_community_cache')||'[]')}catch{state.community=[]}renderCommunity();toast('Community offline cache mode')});
}
$('#chatForm').onsubmit=async e=>{e.preventDefault();const text=$('#chatInput').value.trim();if(!text)return;if(!state.user){toast('First continue as student');return}$('#chatInput').value='';if(state.firebase){await state.api.addDoc(state.api.collection(state.db,'messages'),{text,uid:state.user.uid,authorName:state.user.displayName||'Student',createdAt:state.api.serverTimestamp()})}else addMessage({text,uid:state.user.uid,authorName:state.user.displayName,createdAt:Date.now()})};
$('#askDoubtBtn').onclick=()=>$('#doubtDialog').showModal();$('#closeDialog').onclick=()=>$('#doubtDialog').close();$('#doubtForm').onsubmit=async e=>{e.preventDefault();const item={subject:$('#doubtSubject').value,text:$('#doubtText').value.trim(),uid:state.user?.uid||'guest',authorName:state.user?.displayName||'Student',createdAt:state.firebase?state.api.serverTimestamp():Date.now()};if(state.firebase)await state.api.addDoc(state.api.collection(state.db,'doubts'),item);else{state.doubts.unshift(item);localStorage.setItem('rh_doubts',JSON.stringify(state.doubts));renderDoubts()}$('#doubtText').value='';$('#doubtDialog').close();toast('Doubt posted')};

$('#communityForm').onsubmit=async e=>{e.preventDefault();if(!state.user)return toast('Pehle apna naam daal kar login karein');const text=$('#communityText').value.trim();if(!text)return;if(!state.firebase||!state.api)return toast('Community connect हो रही है — फिर try करें');const a=state.api;try{await a.addDoc(a.collection(state.db,'community_posts'),{uid:state.user.uid,name:state.user.displayName||'Student',text:text.slice(0,1000),reactions:{},comments:[],createdAt:a.serverTimestamp()});$('#communityText').value='';toast('Community post published ✓')}catch(err){console.error(err);toast(navigator.onLine?'Community permission publish करनी है':'Offline — text safe रखें और online होकर post करें')}};
$('#adminMaterialForm').onsubmit=async e=>{e.preventDefault();if(!state.isAdmin)return toast('Admin access required');const a=state.api;await a.addDoc(a.collection(state.db,'materials'),{title:$('#adminMatTitle').value.trim(),description:'Synced by '+ADMIN_NAME,subject:$('#adminMatSubject').value,folder:$('#adminMatFolder').value,type:'PDF',url:$('#adminMatUrl').value.trim(),size:'Drive/R2',sourceApp:'RATHOD HUB shared catalog',adminName:ADMIN_NAME,uploadedBy:ADMIN_NAME,createdAt:a.serverTimestamp()});e.target.reset();toast('Material synced ✓')};
$('#adminSongForm').onsubmit=async e=>{e.preventDefault();if(!state.isAdmin)return toast('Admin access required');const a=state.api;await a.addDoc(a.collection(state.db,'songs'),{title:$('#adminSongTitle').value.trim(),audioUrl:$('#adminSongUrl').value.trim(),driveFileId:$('#adminSongDrive').value.trim(),status:'ready',sourceApp:'RATHOD HUB shared catalog',adminName:ADMIN_NAME,uploadedBy:ADMIN_NAME,createdAt:a.serverTimestamp()});e.target.reset();toast('Song synced ✓')};
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));openView(location.hash.slice(1)||'home');initFirebase();
